# Homework due January 26 - Python and Numpy Introduction

There are 6 questions in this assignment and all questions are weighted the same.

### Question 0: Example

This is a sample question and solution. (There is no need for you to do anything here except read.)

Task: Create a list of multiples of 5 from 0 to 100 using two different methods: a for loop with append and a list comprehension statement.

In [ ]:
##Sample Question Cell

mult5=[]
## Add elements to this list to get all multiples of 5 from 0 to 100 
## using a for loop and append statements.
???

## Use list comprehension to create the same list. 
mult_5= ???

## Then check if both objects are the same 
mult5 ???   mult_5

In [ ]:
##Sample Answer Cell

mult5=[]
## Add elements to this list to get all multiples of 5 from 0 to 100 
## using a for loop and append statements.
for i in range(21):
    mult5.append(5*i)
print(mult5)

## Use list comprehension to create the same list. 
mult_5= [5*i for i in range(21)]
print(mult_5)

## Then check if both objects are the same 
mult5==mult_5

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


True

### Question 1: Python Functions
    
Task: 
1. Write a Python function that will read in a list of numbers and return the sum of every other number in the list starting with the first entry. Any variables your function needs should be defined inside your function.
2. Apply your function to the test_list provided.

In [ ]:
## Write your function here.
def add_every_other(list):
  x = 0
  for i in range(len(list)):
    if(i%2 == 0):
      x += list[i]
  print(x)

## Apply your function and show that it works. 
test_list=[2,9,5,4,1,3,6]

add_every_other(test_list)

14


### Question 2: Lists

Tasks:
1. Create a new list which contains all the numbers in old_list which are congruent to 0 mod 3 using a list comprehension.
2. Use appropriate slicing (that is, use :) to print the last three numbers of the original list.
3. Use appropriate slicing to print the middle five numbers of the original list. 
4. Print all the numbers from old_list in reverse order.


In [ ]:
## The starting list.
old_list = [5,9,4,18,22,2,31,42,98,45,29]
## create new list here of numbers in old_list which are congruent to 0 mod 3.
new_list=[]
for i in range(len(old_list)):
  if old_list[i]%3 == 0:
    new_list.append(old_list[i])

## print last three
print(old_list[-3:])

## print middle five
mid = int(len(old_list)/2)
print(old_list[mid-2:mid+3])

## print in reverse order
print(old_list[::-1])

[98, 45, 29]
[18, 22, 2, 31, 42]
[29, 45, 98, 42, 31, 2, 22, 18, 4, 9, 5]


### Question 3: Dictionaries
    
Tasks: 
1. Create a birthday dictionary with 5 people and their birthdays. Enter names and dates as strings. Neither the people nor the birthdays need to be real. 
1. Add a sixth person and their birthday to the dictionary.
1. Print all names in the dictionary.
1. Print all birthdays from the dictionary.
1. Use the format command to pick one entry from your dictionary and write a sentence about that person and their birthday.


In [ ]:
## Create a dictionary with 5 names.
birthday={
    "Maggie":"July 9 2000",
    "Lizzie":"November 18 2001",
    "Abby":"June 11 2003",
    "Alex":"June 18 2004",
    "Kaecey":"June 22 1977"
}

## Add a 6th name to the dictionary.
birthday["Ben"] = "May 20 1975"

## Print all names in the dictionary.
print(birthday.keys())

## Print all birthdays in the dictionary.
print(birthday.values())

## Use format command (using {} for variables in your dictionary) to write a sentence about that person and their birthday.
print("The birthday of Lizzie is {}".format(birthday["Lizzie"]))

dict_keys(['Maggie', 'Lizzie', 'Abby', 'Alex', 'Kaecey', 'Ben'])
dict_values(['July 9 2000', 'November 18 2001', 'June 11 2003', 'June 18 2004', 'June 22 1977', 'May 20 1975'])
The birthday of Lizzie is November 18 2001


### Question 4 - Creating Vectors and Matrices

In the cell below please create the vectors and matrices as described in the comments.

In [ ]:
import numpy as np
original_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Create a column vector that contains all of the elements in the original matrix in order
col_vec1= np.array(original_matrix)
col_vec1 = col_vec1.reshape(col_vec1.size,1)
print(col_vec1)
print()

# Create a 2x2 submatrix of original_matrix.
sub_matrix = original_matrix[0:2,1:3] 
print(sub_matrix)
print()

# Find a the scalar that is at the center of the original_matrix
scalar = original_matrix[3//2, 3//2]
print(scalar)
print()

# Find the matrix product between the original_matrix and the first three elements of 
# your column vector
mat_prod = np.dot(original_matrix, col_vec1[0:3])
print(mat_prod)
print()

# use BROADCASTING to multiply each column in original_matrix by the first three elements of
# your column vector
mat_brod = original_matrix*col_vec1[0:3]
print(mat_brod)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[[2 3]
 [5 6]]

5

[[14]
 [32]
 [50]]

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


### Question 5 - Matrix Operations

In [ ]:
# Given the following definitions

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.array([[2],[4],[6]])


In [ ]:
import numpy as np
# Construct two matrices, A and B, where np.matmul(A,B) performs regular matrix multiplication.
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2],[4],[6]])
print('A*b: \n', np.matmul(A,b))
print()

# Construct two matrices, A and B, where np.matmul(A,B) will not work and explain why it doesn't work.
A = np.array([[2],[4],[6]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Dimensions of A: ', A.shape)
print('Dimensions of B: ', B.shape)
#print(np.matmul(A,B))
# Matrix mult requires c1 to equal r2. Since the number of columns of A doesn't match the
# number of rows of B, matrix mult won't work. 
print()

# Construct two matrices, A and B, where np.matmul(A,B) uses broadcasting and explain how the broadcasting works.
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2,3]])

# Give three different examples exploring the different uses of np.dot().
# 1) vector dot product
# 2) matrix multiplication
# 3) broadcasting 

# 1)
X = np.array([1,2,3])
print('Vector dot product: ', np.dot(X, X))
print()

# 2)
Y = np.array([[1,2],[3,4]])
Z = np.array([[1],[2]])
print('Matrix mult: \n', np.dot(Y,Z))
print()

# 3)
M = np.array([[1,2],[3,4]])
N = np.array([1,2])
print('Broadcasting: \n', np.dot(M,N))
print()

# Explore the axis command to find the sum of each of the columns and rows for matrix A.
print('Matix A: \n', A)
print('Row sum ', np.sum(A, axis = 0))
print('Column sum ', np.sum(A, axis = 1))
print()

# Explain what the following command does and what the shapes of all the sub elements are.
# Check the shape of C and explain why it makes sense. 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[2],[4],[6]])
C = np.dot( np.add( np.matmul(A,b),b ).T, b )
t = np.add(np.matmul(A,b), b).T
print('A: \n', A, '\n')
print('b: \n', b, '\n')
print('np.matmul(A,b) = A*b = \n')
print(np.matmul(A,b), '\n')
print('Add b to the matrix above \n')
print(np.add(np.matmul(A,b),b), '\n')
print('Transpose the resulted matrix: \n')
print(np.add(np.matmul(A,b), b).T, '\n')
print('Dotting the resulted matrix with by: \n')
print(np.dot(np.add(np.matmul(A,b),b).T, b), '\n')
print('Shape of the final matrix, C: ', C.shape)
print('The shape of the matrix until transposed: ', t.shape)
print('The shape of b is: ', b.shape)
print('The shapes of the arrays are valid for matrix multiplication')




A*b: 
 [[ 28]
 [ 64]
 [100]]

Dimensions of A:  (3, 1)
Dimensions of B:  (3, 3)

Vector dot product:  14

Matrix mult: 
 [[ 5]
 [11]]

Broadcasting: 
 [ 5 11]

Matix A: 
 [[2]
 [4]
 [6]]
Row sum  [12]
Column sum  [2 4 6]

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b: 
 [[2]
 [4]
 [6]] 

np.matmul(A,b) = A*b = 

[[ 28]
 [ 64]
 [100]] 

Add b to the matrix above 

[[ 30]
 [ 68]
 [106]] 

Transpose the resulted matrix: 

[[ 30  68 106]] 

Dotting the resulted matrix with by: 

[[968]] 

Shape of the final matrix, C:  (1, 1)
The shape of the matrix until transposed:  (1, 3)
The shape of b is:  (3, 1)
The shapes of the arrays are valid for matrix multiplication


### Question 6 - Explore numpy!

Below are a few more useful commands. Use the ? help to see if you can figure out what the commands do. Create a numpy object with each of these commands and explain what input is necessary and what output it produces.

In [ ]:
np.empty?

In [ ]:
np.zeros?

In [ ]:
np.zeros_like?

In [ ]:
np.diag?

In [ ]:
np.eye?