# Introduction to Jupyter Notebooks

This is a Jupyter notebook. A Jupyter notebook is an interactive environment divided into cells. 

### Cells have multiple modes. 
- Code for calcuations.
- Markdown for text formatting

Cells are activated with shift/return or the Run command in top menu.
Juypter notebooks are most commonly used with Python, but support multiple programming languages.  

**Google colab** is a notebook stored in Google Drive. 

Instructions on how to get set-up in Colab (and installing Jupyter notebooks if desired) and submitting HW via Colab are given in a video on the Moodle page.


In [5]:
2+2

4

In [2]:
2*3

6

In [3]:
2^3
##What??

1

In [4]:
2**3

8

Note: ^ is Binary xor, not exponentiation, in Python: 10 xor 11 = 01

# Formatting

Headers use the "#" symbol
# Header1
## Header2
### Header3

##### Unordered lists
- use hypthen
+ or plus
* or asterisk
* Note: Need the space after symbol

##### Ordered lists
1. use number followed by period
6. The actual number doesn't matter except that the first number must be 1.
 1. a sublist just needs a space or tab, but still uses a number.
 4. the number also doesn't matter here.
    3. But the number does matter here.

##### Different types of Text
- Emphasis/italics use *asterisks* or _underscores_
- Bold uses double **asterisks** or __underscores__
- Strikethrough uses two tildes. ~~strike it out~~

[Link to Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

##### Newlines and Paragraphs.

Leaving an empty line will create a new paragraph (blank space in between). 

Leaving two spaces at the end of the line    
will just create a new line.

##### Mathematical Equations
- Markdown recognizes basic Latex, $f(x)=x^3$
- But not everything. Note how it indicates that it doesn't understand the Latex. \begin{theorem} This is true. \end{theorem}

Colab is even easier for formatting. There are icons for most of the above commands.

# Introduction to Python
-    high level language: optimized for reading by people instead of machines.
- interpreted language: it is not compiled directly to machine code and usually used in an interactive fashion.
- different from Java or C (no compiling before running)
- can run code as you go, cell by cell in the Jupyter notebook case
- useful for investigations 
- dynamically typed language, similar to languages like JavaScript. No declarations of variables. Whenever you use a variable, you can define it to be an integer on one line and a string on the next line. 
- This class will use Python 3. Make sure to have the right version of Python as your kernel.

In [ ]:
new_var=5
new_var

In [ ]:
new_var="This is a string"
new_var

In [7]:
x=4
y=6
x+y

10

Since notebook is an interactive format, the last line of the cell is output. So we don't need a print statement here. 

In [8]:
x+y
x+y-7

3

Note: only the last line is output. If we wanted both, we would need a print statement.

In [9]:
print(x+y)
print(x+y-7)

10
3


Also note, the cells are stateful, so the value of our variables are preserved between cells.

This also means if we want to go back and change something in a previous cell,
we have to re-execute the cells to make those changes take place. Or use 
restart and run all function under Kernel//Runtime.

Python doesn't require the use of keywords like var to declare a variable name or
semicolons at the end of lines which are commonly used in other languages.
Python leverages white space to understand the scope of functions and
loops and end of line markers to understand the end of statements. 

In [10]:
#Simple Loop
for i in range(5):
    print(i)

0
1
2
3
4


Note the colon and the required indentation (which the notebook did automatically based on the colon.)

In [11]:
#Simple Loop
for i in range(5):
  print(i)  ##Note the indication that the indentation is not correct.

0
1
2
3
4


In [12]:
# if statement
for i in range(10):
    if i==3:  ##difference between = and ==
        print(i)

3


# Python Data Types

### Data types for single item
- integers
- floating point
- strings
- the none type 

In [13]:
type(x)

int

In [14]:
num=6.2
z="Hello"
w=None
print(type(x))
print(type(num))
print(type(z))
print(type(w))
print(type(w))
print(str(num))
print(num==str(num))
print(type(str(num)))
print(int(num))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'NoneType'>
<class 'NoneType'>
6.2
False
<class 'str'>
6


### Data types for multiple items that we will use often
- lists
- dictionaries
    

# Lists

Lists are mutable, so you can change their length, number of elements, and the element values.  
Format square brackets.  
Often created with append statements.   

In [94]:
newlist=[1,2,3,"a","b","c"]
for i in range(4,8):
    newlist.append(i)
newlist

[1, 2, 3, 'a', 'b', 'c', 4, 5, 6, 7]

In [95]:
#This is an example of how to loop through each item in the list.
for item in newlist:
    print(item)

1
2
3
a
b
c
4
5
6
7


In [96]:
## Or another way uses index of list
## While loop
i=0
while( i != len(newlist) ):
    print(newlist[i])
    i = i + 1

1
2
3
a
b
c
4
5
6
7


In [97]:
print(newlist)

[1, 2, 3, 'a', 'b', 'c', 4, 5, 6, 7]


In [98]:
#You can change elements in a list
newlist[0]=3

In [99]:
newlist

[3, 2, 3, 'a', 'b', 'c', 4, 5, 6, 7]

In [100]:
intlist=[1,2,3,4,5,6]

In [101]:
min(intlist)

1

In [102]:
max(intlist)

6

In [103]:
sum(intlist)

21

In [104]:
len(intlist)

6

In [105]:
#What does this do?
[1,2] + [3,4]

[1, 2, 3, 4]

In [106]:
#How about this?
[1,2]*3

[1, 2, 1, 2, 1, 2]

In [107]:
7 in intlist

False

In [108]:
6 in intlist

True

Strings are just lists of characters so same operations work.

In [132]:
message="Hello World"
message+message

'Hello WorldHello World'

In [133]:
message+' '+message

'Hello World Hello World'

In [134]:
message*3

'Hello WorldHello WorldHello World'

In [135]:
'hello' in message

False

# Slicing

Slicing is a useful tool with lists.

In [136]:
print(intlist)
intlist[3:5]

[1, 2, 3, 4, 5, 6]


[4, 5]

In [137]:
print(newlist)
newlist[3:8]

[3, 2, 3, 'a', 'b', 'c', 4, 5, 6, 7]


['a', 'b', 'c', 4, 5]

In [138]:
message[:5]

'Hello'

In [139]:
message[-5:]

'World'

# Dictionaries

Dictionaries are similar to lists and tuples in that they hold a collection of
items, but they're labeled collections which do not have an ordering.
This means that for each value you insert into the dictionary,
you must also give a key to get that value out.
In other languages the structure is often called a map.
Use curly braces and colons.

In [46]:
grades={'Alice':95, 'Bob':90, 'Chris':85}

In [47]:
## no ordering
## This will fail.
grades[0]
## Need to use a key.

KeyError: 0

In [48]:
grades.keys()

dict_keys(['Alice', 'Bob', 'Chris'])

In [49]:
grades['Alice']

95

In [50]:
grades.values()

dict_values([95, 90, 85])

In [52]:
for name in grades:
    print(name)

Alice
Bob
Chris


In [53]:
for name in grades:
    print(grades[name])

95
90
85


In [54]:
for num in grades.values():
    print(num)
    

95
90
85


In [140]:
for name,num in grades.items():
    print(name,num)

Alice 95
Bob 90
Chris 85


In [292]:
## add to dictionary
grades['Dog']=77
grades

{'Alice': 95, 'Bob': 90, 'Chris': 85, 'Dog': 77}

# Python Functions

- begin with def
- must name the function
- specify input variables inside the parenthesis
- end with return
- may return multiple objects

In [141]:
#Example Function
def add_numbers(x,y):
    ##x and y are variable that must be input when calling the function
    return x+y
    ## return specifies the output of the function

In [142]:
add_numbers(4,5)

9

In [148]:
#add_numbers(4,5,6)

# Mini-Functions: Lambda

- no name
- Simple or short-lived functions.
- Define in one line.
- no def, or return
- can only return a single object

In [149]:
def add_one(x):
    return x + 1
add_one(5)

6

In [150]:
(lambda x: x+1)(5)

6

In [151]:
z=[ [2,5],[4,1],[0,7]]
q=sorted(z, key=lambda x: min(x[0],x[1]))
q

[[0, 7], [4, 1], [2, 5]]

# List Comprehensions

Shorthand for creating lists.

In [152]:
#Create a list of even numbers from 0 to 100 with a for loop
my_list1 = []
for number in range(0, 10):
    if number % 2 == 0:    ##What is this doing?
        my_list1.append(number)
my_list1

[0, 2, 4, 6, 8]

In [153]:
#Create a list of even numbers from 0 to 100 with a list comprehension
## simple loop
my_list2= [2*num for num in range(5)]
print(my_list2)

[0, 2, 4, 6, 8]


In [154]:
## combination of for loop and if statement
my_list3 = [number for number in range(0,10) if number % 2 == 0]
my_list3

[0, 2, 4, 6, 8]

In [155]:
my_list1==my_list2

True

Can do multiple loops also!

In [156]:
my_list= [ [i,j] for i in range(3) for j in range(4,9)]
my_list

[[0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8]]

# Numpy and Matrix Operations

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

In [199]:
## A first package
import numpy as np

# Scalars

Theses are just single numbers denoted by lower case constants. In this course we mostly assume real numbers

$$ a, b, c, d \in \mathbb{R} $$

## Vectors

Vectors are 1-D arrays of scalars denoted by bold face lowercase letters. We might think
of vectors in either column or row form.

$$ \mathbf{x} = \left[\begin{array}{@{}c@{}}
    a \\
    b \\
    c 
    \end{array} \right] $$
    
$$ \mathbf{x} = \left[a,b,c \right] $$
    
Vectors are objects in  $n$-dimensional space. In this example,

$$ \mathbf{x} \in \mathbb{R}^3 $$

## Matrix

A matrix is a 2-D array of numbers denoted by bold face uppercase letters

$$ \mathbf{A} = \left[\begin{array}{@{}c,c@{}}
    a & b \\
    c & d \\
    \end{array} \right] $$

$$ \mathbf{B} = \left[\begin{array}{@{}c,c@{}}
    a & b \\
    c & d \\
    e & f 
    \end{array} \right] $$
    
Matrices live in $m \times n$-dimensional space where $m$ is the number of rows and $n$ is the number of columns. Matrices represent linear transformations from $\mathbb{R}^n$ to $\mathbb{R}^m$.



$$ \mathbf{A} \in \mathbb{R}^{2\times 2} \text{ and } \mathbf{b} \in \mathbb{R}^{3\times 2} $$


# Numpy Objects
- 1D arrays (like row vectors)
- 2D arrays (like matrices)
- tensors (higher dimensional arrays)

In [226]:
## 1D arrays in numpy
## Note parentheses and single square brackets
row_vec = np.array([3, 6, 7, 2])
print("Row vector:\n", row_vec,"\nShape\n", row_vec.shape)
## Note that the shape only has one dimension. 

Row vector:
 [3 6 7 2] 
Shape
 (4,)


In [322]:
## Some useful ways to create 1D arrays.
z = np.linspace(0, 2, 6)
print("The shape of {} is {}".format(z,z.shape))
x= np.arange(0,2,.25)
print("The shape of {} is {}".format(x,x.shape))

The shape of [0.  0.4 0.8 1.2 1.6 2. ] is (6,)
The shape of [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75] is (8,)


In [311]:
## Note that numpy 1D arrays are similar to, but different, from lists.
j_list=[2*i for i in range(5)]
j_array=np.arange(0,10,2)
print("The type of {} is {}.".format(j_list,type(j_list)))
print("The type of {} is {}.".format(j_array,type(j_array)))

## visually you can see the difference with the commas.
##We can convert from lists to arrays.
print(np.array(j_list))
## and from arrays to lists. 
print(list(j_array))

The type of [0, 2, 4, 6, 8] is <class 'list'>.
The type of [0 2 4 6 8] is <class 'numpy.ndarray'>.
[0 2 4 6 8]
[0, 2, 4, 6, 8]


In [312]:
## access single elements by index
print(j_array)
print(j_array[2])

[0 2 4 6 8]
4


In [238]:
## Creating 2D arrays in Numpy.
## These correspond to matrices.
## NOTE the parentheses and double square brackets

MAT = np.array([[3,6,7,2],[1,2,3,4]])
print("Matrix 1:\n", MAT,"\nShape\n", MAT.shape)

MAT2=np.array([[3, 6, 7, 2]])
print("\nMatrix 2:\n", MAT2,"\nShape\n", MAT2.shape)

MAT3=np.array([[3],[6],[7],[2]])
print("\nMatrix 3:\n", MAT3,"\nShape\n", MAT3.shape)

print("\nNOTE! 1D objects and 2D objects are very different. Be careful! \n", MAT2,"!=", row_vec )
print(MAT2.shape,"!=",row_vec.shape)

Matrix 1:
 [[3 6 7 2]
 [1 2 3 4]] 
Shape
 (2, 4)

Matrix 2:
 [[3 6 7 2]] 
Shape
 (1, 4)

Matrix 3:
 [[3]
 [6]
 [7]
 [2]] 
Shape
 (4, 1)

NOTE! 1D objects and 2D objects are very different. Be careful! 
 [[3 6 7 2]] != [3 6 7 2]
(1, 4) != (4,)


## Selecting Elements in a Matrix



In [324]:
## Single elements require specifying two components
print(MAT)
print("identifying an element")
print(MAT[1,3])
## identify a row
print("identifying a row")
print(MAT[1])
## identify a column
print("identifying a column")
print(MAT[:,2])
##Remember we index from zero!

[[3 5 7 9]
 [1 2 3 4]]
identifying an element
4
identifying a row
[1 2 3 4]
identifying a column
[7 3]


In [249]:
MAT4 = np.array([np.arange(3,10,2),np.arange(1,5,1),np.arange(10,0,-3)])
MAT4

array([[ 3,  5,  7,  9],
       [ 1,  2,  3,  4],
       [10,  7,  4,  1]])

In [341]:
## Creating a submatrix
M5=MAT4[0:2,1:3]
M5

array([[5, 7],
       [2, 3]])

In [255]:
M5.shape

(2, 2)

In [256]:
M5.size

4

In [420]:
## 2D arrays have an axis feature
## axis=0 performs column-wise operations
## axis=1 performs row-wise operations
print(MAT4)
print(np.max(MAT4))
print(np.max(MAT4,axis=0)) ##max for each column
print(np.max(MAT4, axis=1)) ##max for each row

[[ 3  5  7  9]
 [ 1  2  3  4]
 [10  7  4  1]]
10
[10  7  7  9]
[ 9  4 10]


<h3> Transpose </h3>

In [268]:
# Matrix transpose - exchanges the rows and columns
print(MAT4.T)

[[ 3  1 10]
 [ 5  2  7]
 [ 7  3  4]
 [ 9  4  1]]


# Addition

- In linear algebra, adding matrices only applies to matrices of the same shape.
- but numpy will broadcast to matrices of different shapes if possible.
- element-wise operation

In [331]:
## broadcasting
## numpy is efficient at broadcasting to all components
print(MAT)
print(MAT-3)
## Note this doesn't work for lists.
#print(j_list)
#print(j_list+5)
print(np.subtract(MAT,3))

[[3 5 7 9]
 [1 2 3 4]]
[[ 0  2  4  6]
 [-2 -1  0  1]]
[[ 0  2  4  6]
 [-2 -1  0  1]]


In [330]:
## Adding matrices of the same shape
print(MAT+MAT)
print(np.add(MAT,MAT))
#print(MAT+MAT4)

#  The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).

[[ 6 10 14 18]
 [ 2  4  6  8]]
[[ 6 10 14 18]
 [ 2  4  6  8]]


In [337]:
## Adding matrices with different shapes
## will broadcast if dimensions are compatible
print("matrix 1 \n", MAT)
print("matrix 2 \n", MAT2)
print("sum \n",MAT+MAT2)

matrix 1 
 [[3 5 7 9]
 [1 2 3 4]]
matrix 2 
 [[3 6 7 2]]
sum 
 [[ 6 11 14 11]
 [ 4  8 10  6]]


In [380]:
## Adding matrices with different shapes
## will broadcast if dimensions are compatible
print("matrix 1 \n", MAT)
print("matrix 3 \n", MAT3)
#print("sum \n",MAT+MAT3)

matrix 1 
 [[3 5 7 9]
 [1 2 3 4]]
matrix 3 
 [[3]
 [6]
 [7]
 [2]]


When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when

1. they are equal, or
1. one of them is 1

# Multiplication

- In linear algebra, scaler multiplication and matrix multiplication 
- For matrix multiplication A*B only works if A is an $n \times m$ matrix and B is an $m \times r$ matrix. It will produce an $n \times r$ matrix.
$$  \left[\begin{array}{@{}c,c@{}}
    a & b \\
    c & d \\
    e & f 
    \end{array} \right] * \left[\begin{array}{@{}c}
    g  \\
    h  \\
    \end{array} \right] =  
    \left[\begin{array}{@{}c}
    ag+bh  \\
    cg+dh  \\
    eg+fh  \\
    \end{array} \right]$$
- numpy has scaler multiplication, matrix multiplication, element-wise multiplication, and  broadcasting. 
- mp.matmul(A,B) for matrix multiplication. This is not the same as A*B.

In [381]:
#Hadmard Product - Element Wise
print(MAT)
##scaler multiplcation
print(MAT*3)
## Hadmard Product - Element Wise
print(MAT*MAT)
## broadcasting
print(MAT2)
print(MAT*MAT2)

[[3 5 7 9]
 [1 2 3 4]]
[[ 9 15 21 27]
 [ 3  6  9 12]]
[[ 9 25 49 81]
 [ 1  4  9 16]]
[[3 6 7 2]]
[[ 9 30 49 18]
 [ 3 12 21  8]]


In [383]:
# Matrix Multiplication
print(MAT.shape)
print(MAT2.shape)
#print(np.matmul(MAT,MAT2))

(2, 4)
(1, 4)


In [354]:
print(MAT.shape)
print(MAT2.T.shape)
print(np.matmul(MAT,MAT2.T))

(2, 4)
(4, 1)
[[106]
 [ 44]]


# Dot Product

- In linear algebra, dot products are for two vectors and produce a scaler
$$ [a,b,c] \cdot [e,f,g]=ae+bf+cg $$
- numpy has np.dot(A,B)
- if A,B are 1D arrays this will be the vector dot product
- if A,B are 2D matrices this will be matrix multiplication (same as np.matmul())
- if A is 2D matrix and B is 1D array then it will broadcast dot product over corresponding axes

In [398]:
# Vector dot products
## For 1D arrays, it corresponds to vector dot product
print("for 1D arrays:")
print("For {} np.dot(j_array,j_array) is {}".format(j_array,np.dot(j_array,j_array)))

## For matrices of appropriate sizes, it is the same as matmul.
print("\nfor matrices:")
print("For \n{} and \n{}\n np.dot(MAT,MAT2.T) is\n {}".format(MAT,MAT2.T, np.dot(MAT,MAT2.T)))

## It will also broadcast
print("\nfor matrices and 1D arrays:")
print(MAT)
print(j_array[0:4])
print(np.dot(MAT,j_array[0:4]))

for 1D arrays:
For [0 2 4 6 8] np.dot(j_array,j_array) is 120

for matrices:
For 
[[3 5 7 9]
 [1 2 3 4]] and 
[[3]
 [6]
 [7]
 [2]]
 np.dot(MAT,MAT2.T) is
 [[106]
 [ 44]]

for matrices and 1D arrays:
[[3 5 7 9]
 [1 2 3 4]]
[0 2 4 6]
[92 40]


In [376]:
3*0+2*5+4*7+6*9

92

<h3> Reshape </h3>

In [416]:
# Sometimes we need to reshape our data so that operations work properly

print(MAT)
k=j_array[0:4]
print(k)

mult1=np.matmul(MAT,k)
print("{} has shape {}".format(mult1,mult1.shape))

k=k.reshape(4,1)
mult2=np.matmul(MAT,k)
print("{} has shape {}".format(mult2,mult2.shape))

# Reshape this so that it is a column vector
print(MAT.reshape(MAT.size,1))

print(MAT.reshape(4,2))
# Or we could do it this way
print(MAT.reshape(-1,2)) # the -1 says to use an many rows as needed

newmat=(np.arange(0,9,1).reshape(3,3))
print(newmat)

[[3 5 7 9]
 [1 2 3 4]]
[0 2 4 6]
[92 40] has shape (2,)
[[92]
 [40]] has shape (2, 1)
[[3]
 [5]
 [7]
 [9]
 [1]
 [2]
 [3]
 [4]]
[[3 5]
 [7 9]
 [1 2]
 [3 4]]
[[3 5]
 [7 9]
 [1 2]
 [3 4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
